### ISSUE TITLE
xarray

### ISSUE THREAD

**Issue by jklenzing** [jklenzing/sami2py#63]
**Is your feature request related to a problem? Please describe.**
Currently, data variables are stored directly under the model class.  While the 0.1.0 code has unique number of points in each dimension, this may not always be the case. 

**Describe the solution you'd like**
A migration to an `xarray` dataset would allow for a more self-consistent data access, and could be better compatible with pysat.  Also allows easy sorting of data by solar local time.

**Comment by scivision** [comment]
Another nice thing about xarray is bounded nearest neighbor interpolation for time. Since distinct instruments don't observe with exactly the same cadence. The "bounded" is from you can set a maximum timedelta so that you don't have a nearest neighbor from an excessive amount of time away  (accidentally loaded file for one sensor from wrong year or month for example)

**Comment by jklenzing** [comment]
Closing with merge of #75.
